version: "3.8"

services:
  namenode:
    image: apache/hadoop:3.3.6
    platform: linux/amd64
    container_name: namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop

  datanode:
    image: apache/hadoop:3.3.6
    platform: linux/amd64
    container_name: datanode
    hostname: datanode
    command: ["hdfs", "datanode"]
    depends_on:
      - namenode
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop

  resourcemanager:
    image: apache/hadoop:3.3.6
    platform: linux/amd64
    container_name: resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    depends_on:
      - namenode
      - datanode
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop

  nodemanager:
    image: apache/hadoop:3.3.6
    platform: linux/amd64
    container_name: nodemanager
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    depends_on:
      - resourcemanager
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
