{
 "title": "Traffic_dashboard",
 "time": { "from": "2019-08-02T18:30:00.000Z", "to": "2019-12-03T18:29:59.000Z" },
 "panels": [
  {
   "title": "Sensor Availability",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\n  availability_percent\nFROM sensor_availability\nORDER BY date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Daily Peak and Average Volumes",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\n  -- This string for our X-axis label\n  to_char(date, 'YYYY-MM-DD') AS \"metric\",\n  \n  peak_volume AS \"Peak Volume\",\n  \n  -- Keep the timestamp for the Time Filter\n  date::timestamp AS \"time_filter\"\nFROM daily_stats\nWHERE $__timeFilter(date::timestamp)\nORDER BY date ASC"
    }
   ]
  },
  {
   "title": "Traffic Flow per Sensor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\n  window_start AS \"time\",\n  avg_volume AS \"value\",\n  CAST(sensor_id AS TEXT) AS \"metric\"\nFROM hourly_stats\nWHERE $__timeFilter(window_start)\nORDER BY window_start ASC"
    }
   ]
  }
 ]
}